<h1>О сайте</h1>

OpenPlayer - это удобный онлайн аудиоплеер, работающий на базе вконтакте.ру. Также OpenPlayer является проектом с открытым исходным кодом, и каждый может установить его на свой хостинг.

<ul>
	<li><a href="/discuss">Страница обсуждения на плеере</a></li>
	<li><a siteload="siteload" target="_blank" href="http://bonart.org.ua/oplayer">Страница проекта</a></li>

	<li><a siteload="siteload" target="_blank" href="https://github.com/uavn/oplayer">GitHub</a></li>
	<li><a siteload="siteload" target="_blank" href="https://twitter.com/#!/openwebplayer">Twitter</a></li>
	<li><a siteload="siteload" target="_blank" href="https://plus.google.com/100300191451326989757/posts/euFWxpauzgh">G+</a></li>
	<li><a siteload="siteload" target="_blank" href="http://vk.com/openwebplayer">Вконтакте</a></li>
	<li><a siteload="siteload" target="_blank" href="http://www.facebook.com/groups/145224552223981/">Facebook</a></li>
</ul>

По вопросам платной разработки (доработки) обращайтесь к разработчику (<a href="http://bonart.org.ua/contacts">http://bonart.org.ua/contacts</a>).

<h2>Помощь проекту:</h2>

<?php include ROOT . '/view/donate.phtml' ?>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=355710714479951";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like-box" data-href="http://www.facebook.com/OpenPlayer" data-width="292" data-colorscheme="dark" data-show-faces="true" data-stream="false" data-header="true"></div>