<h1>Правообладателям</h1>

<?php $email = $app['conf']->getOption('app', 'adminemail') ?>

Сайт <a href="<?php echo $app['conf']->getOption('app', 'baseHref') ?>"><?php echo $app['conf']->getOption('app', 'baseHref')?></a> работает на базе движка <a siteload="siteload" target="_blank" href="https://github.com/uavn/openplayer">Open Player</a>, работает через публичный <a siteload="siteload" target="_blank" href="http://vk.com/developers.php?oid=-1&p=audio.search">API Вконтакте.ру</a> и не хранит музыку на своих серверах. <?php if ($email) : ?>По любым вопросам обращайтесь к <a href="mailto:<?php echo $email ?>">администрации сайта</a>.<?php endif ?>