<h3>Топ исполнителей</h3>

<table id="topArtists">
    <tr>
        <?php foreach ( $artists->artists->artist as $i => $artist ): ?>
            <td height="11%" width="11%">
<a title="Слушать <?php echo $artist->name ?> онлайн" href="/search/<?php echo urlencode(str_replace("/", " ", $artist->name)) ?>" class="">
                <div class="ar pic">
                <span class="title"><?php echo $artist->name ?></span>
<img class="lazy" src="<?php echo $artist->image[2]->{"#text"} ?>">
                </div>
</a>
            </td>
            
            <?php $i++ ?>
            <?php if ( 0 == ($i % 5) ): ?>
                </tr><tr>
            <?php endif ?>
        <?php endforeach ?>
    </tr>
</table>
