<!DOCTYPE html>
<html>
    <head>
        <title><?php echo seo_title() ?></title>
        <meta name="charset" value="UTF-8" />

        <base href="<?php echo $app['conf']->getOption('app', 'baseHref') ?>"/>

        <meta name="description" content="<?php echo seo_description() ?>" />
        <meta name="keywords" content="<?php echo seo_keywords() ?>" />

        <link rel="shortcut icon" href="/web/img/fav.png" />
        <link rel="icon" href="/web/img/fav.png"/>

        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>

        <script type="text/javascript" src="/web/js/jPlayer/jquery.jplayer.min.js"></script>

        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
        <link href="/web/css/style.css" rel="stylesheet" media="all" />
    
        <?php include ROOT . '/personalization/placeholder/head.phtml' ?>
    </head>

    <body>
        <div class="user" id="part_menu">
            <?php include 'part/menu.phtml' ?>
        </div>
        
        <div class="head">
            <div class="dib">
                <img src="/web/img/logo.png"/>
            </div>

            <div class="search">
                <form onsubmit="return Search.search(this)">
                    <input id="q" type="text" name="q" value="" placeholder="Поиск"/>
                </form>
            </div>
        </div>
        
        <div class="content opdiv" id="content">
            <?php include ROOT . '/personalization/placeholder/content_top.phtml' ?>
            <?php echo $content ?>
            <?php include ROOT . '/personalization/placeholder/content_bottom.phtml' ?>
        </div>
        
        <div class="sidebar" style="border: 1px solid #333;">
            <div class="opdiv">
                <?php include 'player.phtml' ?>
                <div id="trackname"></div>
            </div>
            
            <?php include ROOT . '/personalization/placeholder/sidebar_top.phtml' ?>

            <div id="playlists">
                <?php echo playlists(); ?>
            </div>

            <div class="opdiv">
                <h3>Last.fm top 20</h3>

                <?php echo lastfmchart(); ?>
            </div>

            <div class="opdiv">
                <h3 onclick="$('#easterEgg').toggle()">Помощь проекту OpenPlayer</h3>

                <div id="easterEgg" style="display:none">
                    <!-- Jimmy is here -->
                    :-)<br/><br/>
                    <img src="http://dl.dropbox.com/u/10902867/jimmy.jpg"/>

                </div>

                <?php include 'donate.phtml' ?>
            </div>
            
            <?php include ROOT . '/personalization/placeholder/sidebar_bottom.phtml' ?>
        </div>

        <div style="clear:both"></div>

        <div class="footer opdiv">
            <div style="margin-bottom:10px">
                Разработчик <a siteload="siteload" target="_blank" href="http://bonart.org.ua">Артём Бондаренко</a>.
            </div>

            <div style="margin-bottom:10px">
                Работает на базе 
                <a target="_blank" siteload="siteload" href="https://github.com/uavn/oplayer">OpenPlayer</a>,
                <a target="_blank" siteload="siteload" href="http://silex.sensiolabs.org">Silex PHP Framework</a>,
                <a target="_blank" siteload="siteload" href="http://phpactiverecord.org">PHPActiveRecord</a>,
                <a target="_blank" siteload="siteload" href="https://github.com/whiteoctober/Pagerfanta">Pagerfanta</a>.
            </div>
            
            <?php include ROOT . '/personalization/placeholder/footer_bottom.phtml' ?>
        </div>

        <script type="text/javascript">
            var Search = {
                search: function() {
                    var val = $('#q').val();

                    Site.load("/search/"+(val.replace(/\//, ' ')), 1);
                    return false;
                }
            }

            var Loading = {
                on: function() {
                    $('#loading').fadeIn('fast');
                },

                off: function() {
                    $('#loading').fadeOut('fast');
                }
            }

            var User = {
                login: function(form) {
                    var data = $(form).serialize();

                    Loading.on();
                    $.ajax({
                        url: $(form).attr('action'),
                        data: data,
                        type: 'post',

                        success: function(data) {
                            User.reloadUserParts();
                            Site.load("/", 1);
                        }
                    });

                    return false;
                },

                logout: function() {
                    Loading.on();
                    $.ajax({
                        url: "/user/logout",
                        type: 'post',

                        success: function(data) {
                            User.reloadUserParts();
                        }
                    });
                },

                reloadUserParts: function() {
                    $('#part_menu').load("/part/menu");
                    Controls.init();
                    reloadPlaylists();
                    Loading.off();
                }
            }

            var Controls = {
                init: function() {
                    $('.x-pladd').unbind('click');
                    $('.x-pladd').click(function() {
                        var self = this;
                        $('.plslist').remove();
                        $.ajax({
                            url: "/plslist",
                            success: function( resp ) {
                                $($(self).parents('.x-track').find('.pladdcont')).append(resp);
                            }

                        });
                    });

                    $('.x-pltrackdel').unbind('click');
                    $('.x-pltrackdel').click(function() {
                        if ( confirm("Уверен?") ) {
                            var self = this;
                            var playlistId = $(this).parents('.pl').data('id');
                            var vkId = $(this).parents('.x-track').data('vkid');

                            $.ajax({
                                url: "/user/pltrackremove",
                                type: "post",
                                data: {
                                    playlistId: playlistId,
                                    vkId: vkId
                                },
                                success: function( resp ) {
                                    $(self).parents('.x-track').remove();
                                }
                            });
                        }
                    });

                    $('.x-lyrics').unbind('click');
                    $('.x-lyrics').click(function() {
                        var lyricsId = $(this).parents('.x-track').data('lyricsid');

                        Loading.on();
                        $.ajax({
                            url: "/getlyrics",
                            data: {
                                lyricsId: lyricsId
                            },
                            success: function( resp ) {
                                $('#popupBlock').html(resp);
                                $('#popupBlock').fadeIn('fast');
                                Loading.off();
                                Controls.init();
                            }
                        });
                    });

                    $('.x-play').unbind('click');
                    $('.x-play').click(function() {
                        var track = $(this).parents('.x-track');
                        var vkid = $(track).data('vkid');

                        $('.x-playing').removeClass('x-playing');
                        $(track).addClass('x-playing');

                        $('.x-pause').hide();
                        $('.x-play').show();

                        $(track).find('.x-pause').show();
                        $(this).hide();

                        if ( vkid == window.curTrack ) {
                            $("#jquery_jplayer_1").jPlayer("play");
                        } else {
                            $('.jp-audio').slideDown();
                            window.curTrack = vkid;
                            window.nowplaying = track;

                            $('#trackname').html($(track).data('artist')+' - '+$(track).data('name'));

                            $("#jquery_jplayer_1").jPlayer("setMedia", {
                                "mp3": "/getsong/"+vkid
                            }).jPlayer("play");
                        }
                    });

                    $('.x-pause').unbind('click');
                    $('.x-pause').click(function() {
                        var track = $(this).parents('.x-track');

                        $(track).find('.x-play').show();
                        $(this).hide();

                        $.jPlayer.pause();
                    });

                    $('.x-icon-link').unbind('click');
                    $('.x-icon-link').click(function() {
                        var track = $(this).parents('.x-track');

                        prompt("Ссылка на трек", "<?php echo $app['conf']->getOption('app', 'baseHref') ?>track/"+$(track).data('vkid'));
                    });

                    $('#topArtists a').hover(function() {
                        var img = $(this).data('img');
                        $('<img/>', {'src': img, 'css': {'position': 'absolute', 'top': '15px', 'z-index': 100}})
                            .insertBefore($(this));
                    }, function() {
                        $('#topArtists img').remove();
                    });

                    var selector = 'a[href!="javascript:"][siteload!="siteload"]';
                    $(selector).click(function(e) {
                        e.preventDefault();
                        /*  
                        if uncomment the above line, html5 nonsupported browers won't change the url but will display the ajax content;
                        if commented, html5 nonsupported browers will reload the page to the specified link. 
                        */
                      
                        pageurl = $(this).attr('href');
                        Site.load(pageurl, 1);
                        
                        return false;
                    });

                    // Исправляем баг некоторых браузеров 
                    // которые подгружают данные после загрузки страницы
                    var popped = ('state' in window.history && window.history.state !== null), initialURL = location.href;
                    
                    $(window).bind('popstate', function(event) {
                        // Ignore inital popstate that some browsers fire on page load
                        var initialPop = !popped && location.href == initialURL;
                        popped = true;
                        if ( initialPop ) return;
                        
                        Site.load(location.pathname);
                    });

                    $(selector).attr('siteload', 'siteload');
                }
            }

            Controls.init();

            var Site = {
                load: function(href, store) {
                    // to change the browser URL to 'href'
                    if ( store && href != location.href ) {
                        if (  typeof window.history.pushState != 'undefined' ) {
                            // Исправляем баг в Chrome >19 
                            // где данные подгружаются после загрузки страницы
                            history.pushState(null,null,href);
                        } else {
                            // Старые браузеры идут накуй
                        }
                    }

                    Loading.on();
                    $.ajax({
                        url: href,
                        success: function( data ) {
                            $('#content').html(data);
                            Loading.off();
                            Controls.init();
                            
                            // $('#content').fadeOut('fast', function() {
                            //     $('#content').html(data);
                            //     $('#content').fadeIn('fast');
                            //     Loading.off();
                            //     Controls.init();
                            // });                                
                        }
                    });
                },

                init: function() {
                    $("#jquery_jplayer_1").jPlayer({
                        swfPath: "/web/js/jPlayer/",
                        solution: "flash, html",
                        supplied: "mp3",
                        volume: "100",

                        ready: function() {},

                        ended: function() {
                            // add checks if this is the end of page
                            $(window.nowplaying).next().find('.x-play').click();
                        },

                        pause: function() {},
                        play: function() {
                            Loading.off();
                        },

                        mute: function() {},
                        unmute: function() {}
                    });

                    Controls.init();

                    $(document).ready(function() {
                        $('#popupBlock').click(function() {
                            $(this).fadeOut('fast');
                        });
                    });

                    $(document).click(function() {
                        $('.plslist').remove();
                    });
                },

                links: function() {
                    
                }
            }

            Site.init();

            function reloadPlaylists() {
                $.ajax({
                    url: "/user/widget/pl",
                    success: function( resp ) {
                        $('#playlists').html(resp);
                        Controls.init();
                    }
                });
            }

$($('.sidebar .opdiv').get(0)).attr('id', 'plpl');
var el = $('#plpl').get(0);
$(el).parents('div').css({'position':'relative'});
$('#playlists').css({'padding-top':'30px'});
$(el).css({'position':'absolute','width':'100%','z-index':'1000'});
var offset = $(el).offset();
var topPadding = 10;
$(window).scroll(function() {
    if ($(window).scrollTop() > offset.top) {
        $(el).stop().animate({marginTop: $(window).scrollTop() - offset.top + topPadding});
    } else {
        $(el).stop().animate({marginTop: 0});
    }
});

        </script>

        <?php include 'form/popup.phtml' ?>

        <style type="text/css">
        .loading {
            background-color: #ddd; 
            top: 0pt; 
            left: 0pt; 
            right: 0pt; 
            border: 0pt none; 
            bottom: 0pt; 
            position: fixed; 
            opacity: 0.3;
            display: none;
        }

        .loading img {
            position: absolute;
            left: 50%;
            margin-left: -64px;
            top:30%;
        }
        </style>

        <div class="loading" id="loading">
            <img src="/web/img/loading.gif"/>
        </div>
    </body>
</html>


