<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio">
    <div class="jp-type-single">
        <div class="jp-gui jp-interface">
            <span class="jp-controls">
                <?php /*<a title="Previous" href="javascript:" class="j-icon j-prev" id="playPrev">&nbsp;</a>*/ ?>
                <a title="Play" href="javascript:" class="j-icon jp-play x-icons x-icon-play">&nbsp;</a>
                <a title="Pause" href="javascript:" class="j-icon jp-pause x-icons x-icon-pause">&nbsp;</a>
                <?php /*<a title="Next" href="javascript:" class="j-icon j-next" id="playNext">&nbsp;</a>*/ ?>
            </span>

            <span class="jp-current-time"></span>
                
            <div class="jp-progress">
                <div class="jp-seek-bar">
                    <div class="jp-play-bar"></div>
                </div>
            </div>
            
            <span class="jp-duration"></span>

            <span class="jp-time-holder">
            </span>
                
            <?php /*<span class="jp-controls">
                <a title="Mute" href="javascript:" class="j-icon jp-mute" tabindex="1">&nbsp;</a>
                <a title="Unmute" href="javascript:" class="j-icon jp-unmute" tabindex="1">&nbsp;</a>
            </span>*/ ?>
                
            <div class="jp-volume-bar">
                <div class="jp-volume-bar-value"></div>
            </div>

        </div>
    </div>
</div>